### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by galo4kin** [GiacomoTezza/turnipScraper#1]
Service does not work _ (
I`m doing something wrong?

```
~/P/turnipScraper (master ☡=) python3 main.py -d ./chromedriver -n Кит
Driver path selected: ./chromedriver
Name selected: AC
Driver initialized and site reached
Found 0 islands
Traceback (most recent call last):
  File "main.py", line 190, in <module>
    if (startQueue(driver, getBestPrice(getBestN(getIslands(driver), 5)), name)):
  File "main.py", line 84, in getBestPrice
    return sorted(islands, key=lambda island: island.bells)[-1]
IndexError: list index out of range
```

**Comment by GiacomoTezza** [comment]
@galo4kin Thank you for for reporting the issue. I am already aware of the problem and I am working on the implementation of the resolution of this issue. The problem is caused by a change made on the site that no longer makes it possible to collect information in the same way. In the meantime I suggest you try this [repo](https://github.com/ilbuonmarcio/TurnipMaster) that implements the same operations with a few more options. Thanks again. I hope I helped.
